theme: jekyll-theme-minimal
title: Satnam Singh
description: Satnam Singh's professional website
logo: /images/mad_scientist_small.jpg
url: https://satnam6502.github.io
footer-links:
  github: satnam6502
  twitter: satnam6502
twitter:
  username: satnam6502
  card: summary_large_image
