theme: jekyll-theme-minimal
title: Satnam Singh
layout: personal
title: Satnam Singh
description: Satnam Singh's personal website
logo: images/satnam.jpg
footer-links:
  github: satnam6502
  twitter: satnam6502
